### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by woodsaj** [raintank/graphite-raintank#21]
```
~$ curl -H "X-org-id: XXX" "http://localhost:8888/render?format=json&from=1456392925&targ
et=litmus.google_com.%2A.https.error_state&until=1456392955" 
Traceback (most recent call last):
  File "/usr/share/python/graphite/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/share/python/graphite/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_req
uest
    rv = self.handle_user_exception(e)
  File "/usr/share/python/graphite/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_excep
tion
    reraise(exc_type, exc_value, tb)
  File "/usr/share/python/graphite/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_req
uest
    rv = self.dispatch_request()
  File "/usr/share/python/graphite/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/share/python/graphite/local/lib/python2.7/site-packages/graphite_api/app.py", line 384, in render
    data_store = fetchData(context, paths)
  File "/usr/share/python/graphite/local/lib/python2.7/site-packages/graphite_api/render/datalib.py", line 160, in 
fetchData
    time_info, series = finder.fetch_multi(nodes, startTime, endTime)
  File "/usr/share/python/graphite/local/lib/python2.7/site-packages/graphite_raintank.py", line 186, in fetch_mult
i
    data = self.fetch_from_tank(nodes, start_time, end_time)
  File "/usr/share/python/graphite/local/lib/python2.7/site-packages/graphite_raintank.py", line 220, in fetch_from
_tank
    for result in resp.json():
  File "/usr/share/python/graphite/local/lib/python2.7/site-packages/requests/models.py", line 800, in json
    self.content.decode(encoding), **kwargs
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

The response from MT looks a ok, except for the Interval being set to 0

```
GET /get?to=1456394565&from=1456394535&target=1065.b48b11d376b6b378eb9ca0d2cc743fce&target=1065.d40d0902ba8d8ec0e1e
327a436036d07 HTTP/1.1.
Host: 10.240.78.52:18763.
Connection: keep-alive.
Accept-Encoding: gzip, deflate.
Accept: */*.
User-Agent: graphite_raintank.
.
####
T 10.240.78.52:18763 -> 10.240.0.8:47022 [AP]
HTTP/1.1 200 OK.
Content-Type: application/json.
Date: Thu, 25 Feb 2016 10:03:15 GMT.
Content-Length: 213.
.
[{"Target":"1065.b48b11d376b6b378eb9ca0d2cc743fce","Datapoints":],"Interval":0},{"Target":"1065.d40d0902ba8d8ec0e1e
327a436036d07","Datapoints":[[null,1456394540],[null,1456394550],[null,1456394560]],"Interval":0}]
```

**Comment by Dieterbe** [comment]
notice the `,"Datapoints":]` in MT's json output, that's invalid json and explains the `No JSON object could be decoded` error. i've fixed this in metric tank now.

the interval being 0 seems like an unrelated (but valid) issue in metric tank
